ENTRY(entry)

OUTPUT_FORMAT("binary")

stage2_loc = 0x00008000;

SECTIONS
{
    . = stage2_loc;

    .entry              : { __entry_start = .;      *(.entry)   }
    .text               : { __text_start = .;       *(.text)    }
    .data               : { __data_start = .;       *(.data)    }
    .rodata             : { __rodata_start = .;     *(.rodata)  }
    .bss                : { __bss_start = .;        *(.bss)     }
    
    __end = .;
}